# # if (!require(devtools))
# #   install.packages("devtools")
# # devtools::install_github("jcheng5/leaflet-shiny")
# # shiny::runGitHub("superzip", "jcheng5")
# # install.packages('Rcpp')
# # library(shiny)
# # shiny::runGitHub("shiny-examples", "rstudio", subdir = "063-superzip-example")
# # runGitHub("shiny_example", "rstudio")
# # runApp('C:/study/Projects/shiny/shiny-examples-master/063-superzip-example')
# # runApp('C:/study/Projects/shiny/powerplants')
# # runApp('C:/Users/temp/Dropbox/test/shiny/powerplants')
# # library(leaflet)
# # 
# # pow <- read.csv('C:/Users/temp/Dropbox/test/shiny/powerplants/eGRID2012V1_0_year09_DATA.csv')
# # head(pow)
# library(shiny)
# runGitHub('powerplantLeaflet', 'jianhuaHuang')
# ?runGitHub
# runGitHub('jianhuaHuang/powerplantLeaflet')
# runGitHub("rstudio/shiny_example")
# runGitHub("shiny_example", "rstudio", subdir = "inst/shinyapp/")
# runGitHub("shiny_example", "rstudio")
# runGitHub("shiny_example", "rstudio", subdir = "inst/shinyapp/")
# devtools::install_github("ShinyDash", "trestletech")
# 
# shiny::runGist('3239667')
# install.packages('shiny')
# library(shiny)
# shiny::runGitHub("shiny-examples", "rstudio", subdir = "001-hello")
# shiny::runGitHub("powerplantLeaflet", "JianhuaHuang")
# shiny::runGitHub('JianhuaHuang/powerplantLeaflet')
# # 
# shinyapps::configureApp("powerplants", size="medium")
